language: c

sudo: false

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION: 5.92
    - RACKET_VERSION: 5.93
    - RACKET_VERSION: 6.0
    - RACKET_VERSION: 6.0.1
    - RACKET_VERSION: 6.1
    - RACKET_VERSION: 6.2
    - RACKET_VERSION: HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install -in r7rs-lib --deps search-auto --link $TRAVIS_BUILD_DIR/r7rs-lib
  - raco pkg install -in r7rs-test --deps search-auto --link $TRAVIS_BUILD_DIR/r7rs-test

script:
  - raco test -p r7rs-lib
  - raco test $TRAVIS_BUILD_DIR/r7rs-test/tests/r7rs/chibi/tests/r7rs-tests.rkt
